version: "3.8"

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fraction
      - POSTGRES_PASSWORD=fraction
      - POSTGRES_DB=fraction

volumes:
  postgres_data:
