# Generated by Django 2.2.17 on 2021-01-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('canada', 'Canada'), ('germany', 'Germany'), ('mexico', 'Mexico'), ('usa', 'United States of America'), ('france', 'France')], max_length=50)),
                ('product', models.CharField(choices=[('carretera', 'Carretera'), ('paseo', 'Paseo'), ('velo', 'Velo'), ('vvt', 'VVT'), ('montana', 'Montana'), ('amarilla', 'Amarilla')], max_length=50)),
                ('discount_band', models.CharField(blank=True, max_length=10)),
                ('unit_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
