# Generated by Django 2.2.17 on 2021-01-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Transaction',
        ),
    ]
