# Generated by Django 2.2.17 on 2021-01-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210114_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='manufacturing',
            new_name='manufacturing_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='unit_sold',
            new_name='units_sold',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(choices=[('canada', 'Canada'), ('germany', 'Germany'), ('mexico', 'Mexico'), ('united_states_of_america', 'United States of America'), ('france', 'France')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.CharField(choices=[('carretera', 'Carretera'), ('paseo', 'Paseo'), ('velo', 'Velo'), ('vtt', 'VTT'), ('montana', 'Montana'), ('amarilla', 'Amarilla')], max_length=50),
        ),
    ]
