# Generated by Django 2.2.17 on 2021-01-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210114_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(choices=[('canada', 'Canada'), ('germany', 'Germany'), ('mexico', 'Mexico'), ('united_states_of_america', 'United States of America'), ('france', 'France')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.CharField(choices=[('carretera', 'Carretera'), ('paseo', 'Paseo'), ('velo', 'Velo'), ('vtt', 'VTT'), ('montana', 'Montana'), ('amarilla', 'Amarilla')], max_length=100),
        ),
    ]
