# Generated by Django 2.2.17 on 2021-01-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210114_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount_band',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='units_sold',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
