# Generated by Django 2.2.17 on 2021-01-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210114_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month_name',
            field=models.CharField(default='January', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='month_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.IntegerField(default=2014),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='department',
            field=models.CharField(choices=[('government', 'Government'), ('midmarket', 'Midmarket'), ('channel_partners', 'Channel Partners'), ('enterprise', 'Enterprise')], max_length=100),
        ),
    ]
